src/Entity/Event.php
<?php

namespace App\Entity;

use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Attribute\Groups;
use App\Repository\EventRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: EventRepository::class)]
class Event
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups(["events"])]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    #[Groups(["events"])]
    #[Assert\NotBlank]
    #[Assert\Length(
        min: 3,
        max: 50,
        minMessage: 'Le titre doit au moins faire {{ limit }} caractères de long',
        maxMessage: 'Le titre ne doit pas faire plus de {{ limit }} caractères',
    )]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT)]
    #[Assert\NotBlank]
    private ?string $description = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\Length(
        max: 255,
        maxMessage: 'Le nom de l\'image est trop long',
    )]
    private ?string $picture = null;

    #[ORM\Column(nullable: true)]
    #[Assert\PositiveOrZero]
    private ?int $playersMin = null;

    #[ORM\Column(nullable: true)]
    #[Assert\PositiveOrZero]
    private ?int $playersMax = null;

    #[ORM\Column(length: 255)]
    #[Assert\Length(
        max: 255,
        maxMessage: 'Adresse trop longue',
    )]
    private ?string $address = null;

    #[ORM\Column]
    #[Groups(["events"])]
    private ?float $latitude = null;

    #[ORM\Column]
    #[Groups(["events"])]
    private ?float $longitude = null;

    #[ORM\Column]
    private ?bool $isPublic = null;

    #[ORM\Column]
    #[Assert\NotBlank]
    private ?\DateTimeImmutable $startAt = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $endAt = null;

    #[ORM\ManyToOne(inversedBy: 'events')]
    #[ORM\JoinColumn(nullable: false)]
    #[Groups(["events"])]
    private ?User $host = null;

    #[ORM\ManyToMany(targetEntity: Game::class, inversedBy: 'events')]
    private Collection $games;

    #[ORM\OneToMany(mappedBy: 'event', targetEntity: EventRequests::class, orphanRemoval: true)]
    private Collection $eventRequests;

    public function __construct()
    {
        $this->games = new ArrayCollection();
        $this->isPublic = false;
        $this->eventRequests = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): static
    {
        $this->picture = $picture;

        return $this;
    }

    public function getPlayersMin(): ?int
    {
        return $this->playersMin;
    }

    public function setPlayersMin(?int $playersMin): static
    {
        $this->playersMin = $playersMin;

        return $this;
    }

    public function getPlayersMax(): ?int
    {
        return $this->playersMax;
    }

    public function setPlayersMax(?int $playersMax): static
    {
        $this->playersMax = $playersMax;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): static
    {
        $this->address = $address;

        return $this;
    }

    public function getLatitude(): ?float
    {
        return $this->latitude;
    }

    public function setLatitude(float $latitude): static
    {
        $this->latitude = $latitude;

        return $this;
    }

    public function getLongitude(): ?float
    {
        return $this->longitude;
    }

    public function setLongitude(float $longitude): static
    {
        $this->longitude = $longitude;

        return $this;
    }

    public function isIsPublic(): ?bool
    {
        return $this->isPublic;
    }

    public function setIsPublic(bool $isPublic): static
    {
        $this->isPublic = $isPublic;

        return $this;
    }

    public function getStartAt(): ?\DateTimeImmutable
    {
        return $this->startAt;
    }

    public function setStartAt(\DateTimeImmutable $startAt): static
    {
        $this->startAt = $startAt;

        return $this;
    }

    public function getEndAt(): ?\DateTimeImmutable
    {
        return $this->endAt;
    }

    public function setEndAt(?\DateTimeImmutable $endAt): static
    {
        $this->endAt = $endAt;

        return $this;
    }

    public function getHost(): ?User
    {
        return $this->host;
    }

    public function setHost(?User $host): static
    {
        $this->host = $host;

        return $this;
    }

    /**
     * @return Collection<int, Game>
     */
    public function getGames(): Collection
    {
        return $this->games;
    }

    public function addGame(Game $game): static
    {
        if (!$this->games->contains($game)) {
            $this->games->add($game);
        }

        return $this;
    }

    public function removeGame(Game $game): static
    {
        $this->games->removeElement($game);

        return $this;
    }

    /**
     * @return Collection<int, EventRequests>
     */
    public function getEventRequests(): Collection
    {
        return $this->eventRequests;
    }

    public function addEventRequest(EventRequests $eventRequest): static
    {
        if (!$this->eventRequests->contains($eventRequest)) {
            $this->eventRequests->add($eventRequest);
            $eventRequest->setEvent($this);
        }

        return $this;
    }

    public function removeEventRequest(EventRequests $eventRequest): static
    {
        if ($this->eventRequests->removeElement($eventRequest)) {
            // set the owning side to null (unless already changed)
            if ($eventRequest->getEvent() === $this) {
                $eventRequest->setEvent(null);
            }
        }

        return $this;
    }

    /**
     * Return array of User with status ACCEPTED
     *
     * @return User[]
     */
    public function getAcceptedUsers()
    {
        $users = [];
        $eventRequest = $this->getEventRequests();

        foreach ($eventRequest as $e) {
            if ($e->getStatus() === EventRequests::ACCEPTED) {
                $users[] = $e->getUser();
            }
        }
        return $users;
    }
}

src/Controller/Api/EventController.php
<?php

namespace App\Controller\Api;

use App\Repository\EventRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class EventController extends AbstractController
{
    /**
     * Route qui retourne la liste des événements au format JSON
     * 
     * @param EventRepository $eventRepository
     * @return JsonResponse
     */
    
    #[Route('/api/events', name: 'app_api_events', methods: ["GET"])]
    public function events(EventRepository $eventRepository): JsonResponse
    {
        $events = $eventRepository->findAll();

        return $this->json($events, Response::HTTP_OK, [], ["groups" => "events"]);
    }
}

src/Controller/EventController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Entity\Event;
use App\Form\EventType;
use App\Service\FileUploader;
use App\Repository\EventRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[Route('/evenement')]
class EventController extends AbstractController
{
    public function __construct(
        private FileUploader $fileUploader
    ) {
    }

    /**
     * All Event
     *
     * @param EventRepository $eventRepository
     * @return Response
     */
    #[Route('/', name: 'app_event_index', methods: ['GET'])]
    public function index(Request $request, EventRepository $eventRepository): Response
    {
        $city = $request->get('ville') ?: null;

        return $this->render('event/index.html.twig', [
            'events' => $eventRepository->findByFutureDate(urldecode($city)),
            'passedEvents' => $eventRepository->findByPassedDate()
        ]);
    }

    /**
     * All Event for User, as host or guest
     */
    #[Route('/mes-evenements', name: 'app_event_user', methods: ['GET'])]
    public function userEvent(EventRepository $eventRepository): Response
    {
        /** @var User */
        $user = $this->getUser();

        return $this->render('event/index_user.html.twig', [
            'events' => $eventRepository->findByHostOrGuests($user)
        ]);
    }

    /**
     * Create new event
     *
     * @param Request $request
     * @param EntityManagerInterface $entityManager
     * @return Response
     */
    #[Route('/new', name: 'app_event_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        /** @var User */
        $user = $this->getUser();

        $event = new Event();
        $form = $this->createForm(EventType::class, $event, ['role' => $user->getRoles()[0]]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $event->setHost($this->getUser());

            if (!$event->getAddress()) {
                $event->setAddress($user->getAddress() . ' ' . $user->getCity());
            }

            // Traitement de l'image
            if ($event->isIsPublic()) {
                // Type $imageFile comme un objet UploadedFile
                /** @var UploadedFile $imageFile */
                $imageFile = $form->get('pictureFile')->getData();
                // Si une image est uploadé
                if ($imageFile) {
                    // Utilise Service/FileUploader pour enregistrer l'image
                    $imageFileName = $this->fileUploader->upload($imageFile);
                    // Met à jour la propriété image avec le nouveau nom de l'image
                    $event->setPicture($imageFileName);
                }
            }

            $entityManager->persist($event);
            $entityManager->flush();

            return $this->redirectToRoute('app_event_index', [], Response::HTTP_SEE_OTHER);
        }

        // TODO : Send email to all friends of user when he create an event

        return $this->render('event/new.html.twig', [
            'event' => $event,
            'form' => $form,
        ]);
    }

    /**
     * Delete all events before today
     */
    #[Route('/delete/events', name: 'app_event_delete_past', methods: ['GET'])]
    #[IsGranted('ROLE_ADMIN')]
    public function deleteEventsBeforeToday(EventRepository $eventRepository, EntityManagerInterface $entityManager)
    {
        $events  = $eventRepository->findByPassedDate();

        foreach ($events as $e) {
            $entityManager->remove($e);
        }
        $entityManager->flush();

        $this->addFlash('success', 'Tous les événements antérieurs à aujourd\'hui ont été supprimés');
        return $this->redirectToRoute('app_event_index', [], Response::HTTP_SEE_OTHER);
    }

    /**
     * Show one Event details
     */
    #[Route('/{id}', name: 'app_event_show', methods: ['GET'])]
    public function show(Event $event): Response
    {
        return $this->render('event/show.html.twig', [
            'event' => $event,
        ]);
    }

    /**
     * Edit an Event
     */
    #[Route('/{id}/edit', name: 'app_event_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Event $event, EntityManagerInterface $entityManager, Filesystem $filesystem): Response
    {
        $this->denyAccessUnlessGranted('EVENT_EDIT', $event);

        /**@var User */
        $user = $this->getUser();

        $form = $this->createForm(EventType::class, $event, ['role' => $user->getRoles()[0]]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            if ($event->getAddress() == null) {
                $event->setAddress($user->getAddress() . ', ' . $user->getPostalCode() . ' ' . $user->getCity());
            }

            // Traitement de l'image
            if ($event->isIsPublic()) {
                // Type $imageFile comme un objet UploadedFile
                /** @var UploadedFile $imageFile */
                $imageFile = $form->get('pictureFile')->getData();
                // Si une image est uploadé
                if ($imageFile) {
                    // Supprime l'image actuelle, chemin complet de l'image
                    $filesystem->remove($this->getParameter('images_directory') . '/' . $event->getPicture());
                    // Utilise Service/FileUploader pour enregistrer l'image
                    $imageFileName = $this->fileUploader->upload($imageFile);
                    // Met à jour la propriété image avec le nouveau nom de l'image
                    $event->setPicture($imageFileName);
                }
            }

            $entityManager->flush();

            return $this->redirectToRoute('app_event_index', [], Response::HTTP_SEE_OTHER);
        }

        // TODO : Send email to all guests when an event have changed
        // TODO : Send email to all guests when an event have changed
        // TODO : Send email to all guests when an event have changed

        return $this->render('event/edit.html.twig', [
            'event' => $event,
            'form' => $form,
        ]);
    }

    /**
     * Delete an Event
     */
    #[Route('/{id}', name: 'app_event_delete', methods: ['POST'])]
    public function delete(Request $request, Event $event, EntityManagerInterface $entityManager, Filesystem $filesystem): Response
    {
        $this->denyAccessUnlessGranted('EVENT_EDIT', $event);

        if ($this->isCsrfTokenValid('delete' . $event->getId(), $request->request->get('_token'))) {
            if ($event->getPicture()) {
                // Supprime l'image, chemin complet de l'image
                $filesystem->remove($this->getParameter('images_directory') . '/' . $event->getPicture());
            }
            $entityManager->remove($event);
            $entityManager->flush();
        }


        // TODO : Send email to all guests when an event is delete
        // TODO : Send email to all guests when an event is delete
        // TODO : Send email to all guests when an event is delete


        return $this->redirectToRoute('app_event_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/event/_delete_form.html.twig
<form method="post" action="{{ path('app_event_delete', {'id': event.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ event.id) }}">
    <button class="btn btn-danger rounded-pill">Supprimer</button>
</form>

templates/event/_event_card.html.twig
{% if event.isPublic %}
    {% set city = event.address|split(' ')|last %}
{% else %}
    {% set city = event.host.city %}
{% endif %}


<div class="eventcard card">
    <a href="{{ path('app_event_show', {id: event.id}) }}" style="text-decoration: none">
        <div class="card-header text-center" style="background-color: #1d4b7c; text-decoration: none">
        <b class="text-light fs-4">{{ event.startAt ? event.startAt|format_datetime(pattern="dd MMM", locale='fr')|capitalize }}</b>
        </div>
    </a> 


    <div class="card-body">
        <div class="text-center mb-3">
            <b class="fs-5 blue">{{ event.title|title }}</b>
        </div>
                

        <div class="d-flex justify-content-between">
            <button class="btn btn-sm btn-{{ event.isPublic ? 'success' : 'danger' }}" disabled>{{ event.isPublic ? 'Public' : 'Privé' }}</button>
            <a class="btn btn-sm btn-primary" href="{{ path('app_event_index', {ville: city|url_encode}) }}">{{ city|title }}</a>
        </div>
                
    </div>
</div>

templates/event/_event_line.html.twig
<div class="row rounded-pill m-4 p-3 border border-primary d-flex align-items-center">
    <div class="col-md-3 text-center">
        {{ event.startAt ? event.startAt|format_datetime('medium', 'short', locale='fr')|capitalize }}
        à 
        {% if event.isPublic %}
            {% set city = event.address|split(' ')|last %}
        {% else %}
            {% set city = event.host.city %}
        {% endif %}
        <a class="btn btn-primary rounded-pill" href="{{ path('app_event_index', {ville: city|url_encode}) }}">{{ city }}</a>
    </div>
    <div class="col-md-5">
        <a class="btn btn-primary rounded-pill" href="{{ path('app_event_show', {id: event.id}) }}">{{ event.title|title }}</a>
            par {{ event.host.alias }}
        
    </div>
    <div class="col-md-4">
        {% if not is_granted('EVENT_EDIT', event) and event.isPublic is same as false %}

            {% include "event/_event_status.html.twig" %}
            
        {% endif %}
        {# <a href="{{ path('app_event_show', {'id': event.id}) }}">show</a> #}
        {% if is_granted('EVENT_EDIT', event) %}
            <a class="btn btn-primary rounded-pill" href="{{ path('app_event_edit', {'id': event.id}) }}">Editer</a>
        {% endif %}
    </div>
</div>

templates/event/_event_requests.html.twig
{% if app.user is same as event.host %}
    {% for request in event.eventRequests %}
        <tr>
            <td></td>
            <td colspan="4"><a href="{{ path('app_profil_public', {id: event.host.id}) }}">{{ request.user }}</a> souhaite se joindre à vous</td>
            <td>
            {% if request.status == 'PENDING' %}
                <a href="{{ path('app_event_requests_status', {id: request.id, status: 'ACCEPTED'}) }}" class="btn btn-success rounded-pill">Accepter</a>
                <a href="{{ path('app_event_requests_status', {id: request.id, status: 'REFUSED'}) }}" class="btn btn-danger rounded-pill">Refuser</a>
            {% else %}
                <button class="btn btn-secondary rounded-pill" disabled>{% include 'event/_translate_status_request.html.twig' %}</button>
                <a class="btn btn-danger rounded-pill" href="{{ path('app_event_requests_delete', {id: request.id}) }}"><i class="fa-solid fa-trash-can"></i></a>
            {% endif %}
            </td>
        </tr>
    {% endfor %}
{% endif %}

templates/event/_event_status.html.twig
{% set userRequest = false %}

{# Pour toutes les requests d'un event #}
{% for request in event.eventRequests %}

    {# if user de la request is current user #}
    {% if request.user is same as app.user %}
        <button class="btn btn-secondary rounded-pill" disabled>
            {% include 'event/_translate_status_request.html.twig' %}
        </button>
        {% set userRequest = true %}
        <a class="btn btn-danger rounded-pill" href="{{ path('app_event_requests_delete', {id: request.id}) }}"><i class="fa-solid fa-trash-can"></i></a>
    {% endif %}

{% endfor %}

{% if event.eventRequests|length >= event.playersMax %}
    <button class="btn btn-secondary rounded-pill" disabled>Complet</button>
{% elseif not userRequest %}
    <a href="{{ path('app_event_requests_new', {id: event.id, status: 'PENDING'}) }}" class="btn btn-primary rounded-pill">Participer</a>
{% endif %}

templates/event/_event_table.html.twig
<table class="table">
    {# <thead>
        <tr>
            <th>Date</th>
            <th>Ville</th>
            <th>Evénement</th>
            <th>Type</th>
            <th>Participants</th>
            <th>actions</th>
        </tr>
    </thead> #}
    <tbody>
    {% for event in events %}
        <tr>
            <td>
                {{ event.startAt|format_datetime('medium', 'short', locale='fr')|capitalize }}
            </td>
            <td>
                {% if event.isPublic %}
                    {% set city = event.address|split(' ')|last %}
                {% else %}
                   {% set city = event.host.city %}
                {% endif %}
                <a href="{{ path('app_event_index', {ville: city|url_encode}) }}">{{ city|title }}</a>
            </td>
            <td>
                <a href="{{ path('app_event_show', {id: event.id}) }}">{{ event.title|title }}</a> 
                par <a href="{{ path('app_profil_public', {id: event.host.id}) }}">{{ event.host.alias }}</a>
            </td>
            <td>{{ event.isPublic ? 'Public' : 'Privé' }}</td>
            <td>
                {% if event.isPublic is same as false %}
                    {{ event.acceptedUsers|length }}{% if event.playersMax %}/{{ event.playersMax}}{% endif %}
                {% endif %}</td>
            <td>
                {% if not is_granted('EVENT_EDIT', event) and event.isPublic is same as false %}

                    {% include "event/_event_status.html.twig" %}
                    
                {% endif %}
                {# <a href="{{ path('app_event_show', {'id': event.id}) }}">show</a> #}
                {% if is_granted('EVENT_EDIT', event) %}
                    <a href="{{ path('app_event_edit', {'id': event.id}) }}">Editer</a>
                {% endif %}
            </td>
        </tr>
        {% include "event/_event_requests.html.twig" %}
    {% endfor %}
    </tbody>
</table>

templates/event/_form.html.twig
{{ form_start(form) }}
    {# {{ form_widget(form) }} #}
    <div class="row">

        {% if is_granted('ROLE_ADMIN')  %}
            <div class="col-md-6">
                {{ form_row(form.isPublic) }}
            
                <div class="alert alert-secondary">
                    <b>Pour les événements publics</b>
                    {{ form_row(form.address) }}
                    {{ form_row(form.pictureFile) }}
                </div>
            </div>
        {% endif %}

        <div class="col-md-6 mx-auto">
            <div class="row">
                <div class="col-6">
                    {{ form_row(form.title) }}
                </div>
                <div class="col-6">
                    {{ form_row(form.playersMax) }}
                </div>
            </div>
            <div class="row">
                <div class="col-6">
                    {{ form_row(form.startAt) }}
                </div>
                <div class="col-6">
                    {{ form_row(form.endAt) }}
                </div>
            </div>
            {{ form_row(form.description) }}
        </div>

    </div>
    <div class="text-end">
        <button class="btn btn-primary rounded-pill">Enregistrer</button>
    </div>
{{ form_end(form) }}

templates/event/_translate_status_request.html.twig
{% if request.status == 'PENDING' %} Demande en  cours
{% elseif request.status =='ACCEPTED'%} Demande acceptée
{% else %} Demande refusée  
{% endif %}

templates/event/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Editer {{ event.title }}{% endblock %}

{% block body %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ path('app_home') }}">Accueil</a></li>
            <li class="breadcrumb-item"><a href="{{ path('app_event_index') }}">Evénements</a></li>
            <li class="breadcrumb-item active" aria-current="page">Editer {{ event.title }}</li>
        </ol>
    </nav>

    <section>
        <div class="card">
            <div class="card-header">
                <h1>Editer {{ event.title }}</h1>
                <a class="btn btn-link" href="{{ path('app_event_index') }}">Retour</a>
            </div>
            <div class="card-body">
                {{ include('event/_form.html.twig', {'button_label': 'Update'}) }}
            </div>
            <div class="card-footer text-end">
                {{ include('event/_delete_form.html.twig') }}
            </div>
        </div>
    </section>
{% endblock %}

templates/event/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tous les événements{% endblock %}

{% block body %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ path('app_home') }}">Accueil</a></li>
            <li class="breadcrumb-item active" aria-current="page">Evénements</li>
        </ol>
    </nav>

    <section>
        <div class="">
            <div class="mb-5">
                <h1 class="title">Tous les événements</h1>
                <a class="btn btn-primary rounded-pill" href="{{ path('app_event_new') }}">Créer un événement</a>
                <a class="btn btn-primary rounded-pill" href="{{ path('app_event_user') }}">Mes événements</a>
                {% if is_granted('ROLE_ADMIN') %}
                    {% if passedEvents|length > 0 %}
                        <a class="btn btn-danger rounded-pill" href="{{ path('app_event_delete_past') }}" onclick="return confirm('Supprimer les événements passés ?');">Supprimer les événements passés ({{ passedEvents|length }})</a>
                    {% else %}
                        <button class="btn btn-danger rounded-pill" disabled="disabled">Supprimer les événements passés</button>
                    {% endif %}
                {% endif %}
            </div>
            <div class="">
                {% if events %}
                    {# <div class="row">
                        <div class="col-md-4 col-lg-3">
                            {% for event in events %}
                                {% include "event/_event_card.html.twig" %}
                            {% endfor %}
                        </div>
                    </div> #}
                    {% include "event/_event_table.html.twig" %}


                {% else %}
                    <p>Rien par ici</p>
                {% endif %}
            </div>
        </div>
    </section>
{% endblock %}

templates/event/index_user.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mes événements{% endblock %}

{% block body %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ path('app_home') }}">Accueil</a></li>
            <li class="breadcrumb-item"><a href="{{ path('app_event_index') }}">Evénements</a></li>
            <li class="breadcrumb-item active" aria-current="page">Mes événements</li>
        </ol>
    </nav>

    <section>
        <div class="">
            <div class="mb-5">
                <h1 class="title">Mes événements</h1>
                <a class="btn btn-primary rounded-pill" href="{{ path('app_event_index') }}">Retour</a>
                <a class="btn btn-primary rounded-pill" href="{{ path('app_event_new') }}">Créer un événement</a>
            </div>
            <div class="">
                {% if events %}
                    {% include "event/_event_table.html.twig" %}
                {% else %}
                    <p>Rien par ici</p>
                {% endif %}
            </div>
        </div>
    </section>
{% endblock %}

templates/event/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ event.title }}{% endblock %}

{% block body %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ path('app_home') }}">Accueil</a></li>
            <li class="breadcrumb-item"><a href="{{ path('app_event_index') }}">Evenements</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ event.title }}</li>
        </ol>
    </nav>

    <section>
        <div class="col-8 mx-auto row">

            <div class="col-md-6">
                {% if event.picture %}
                    <img src="{{ asset('images/uploads/' ~ event.picture) }}" alt="{{ event.title }}" class="img-fluid rounded">
                {% else %}
                    <img class="img-fluid rounded" src="{{ asset('images/ohmygame_logo.png') }}" alt="{{ event.title|title }}">
                {% endif %}
            </div>

            <div class="col-md-6">
                <div class="">
                    <span class="badge rounded-pill text-bg-secondary">{{ event.isPublic ? 'Public' : 'Privé' }}</span> 
                    <h1 class="title">{{ event.title|title }} </h1>
                </div>
                <p>
                    {{ event.startAt ? event.startAt|format_datetime('full', 'short', locale='fr')|capitalize }} 
                    par <a href="{{ path('app_profil_public', {id: event.host.id})}}">{{ event.host.alias }}</a>
                </p>
                <p>
                    <button class="btn btn-outline-primary rounded-pill" disabled>{{ event.address }}</button>
                    {% if event.isPublic == false and event.players is defined %} 
                        <button class="btn btn-outline-primary rounded-pill" disabled>{{ event.acceptedUsers|length }}/{{ event.playersMax }} joueurs</button>
                    {% endif %}
                </p>
                <p>{{ event.description|capitalize }}</p>
                <div class="d-block d-flex justify-content-between mt-5">
                    {% if is_granted('EVENT_EDIT', event) %}

                        <a class="btn btn-primary rounded-pill me-2" href="{{ path('app_event_edit', {'id': event.id}) }}">Editer</a>
                        {{ include('event/_delete_form.html.twig') }}

                    {% elseif event.isPublic == false %}  
                        <div class="bg-light border border-3 rounded-5 p-3 d-flex justify-content-between  align-items-center w-100">
                            Ma participation
                            {% if not is_granted('EVENT_EDIT', event) and event.isPublic is same as false %}

                                {% include "event/_event_status.html.twig" %}
                                
                            {% endif %}
                        </div>

                    {% endif %}
                </div>
            </div>
        </div>
    </section>
{% endblock %}