src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Serializer\Attribute\Groups;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email', 'alias'])]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups(["users"])]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    #[Assert\Email(
        message: "L'e-mail {{ value }} n'est pas un e-mail valide.",
    )]
    #[Assert\NotBlank]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 25)]
    #[Assert\NotBlank]
    private ?string $firstname = null;

    #[ORM\Column(length: 25)]
    #[Assert\NotBlank]
    private ?string $lastname = null;

    #[ORM\Column]
    #[Assert\NotBlank]
    private ?\DateTimeImmutable $birthAt = null;

    #[ORM\Column(length: 100)]
    #[Assert\NotBlank]
    private ?string $address = null;

    #[ORM\Column(length: 50)]
    #[Assert\NotBlank]
    private ?string $city = null;

    #[ORM\Column(nullable: true)]
    #[Groups(["users"])]
    private ?float $longitude = null;

    #[ORM\Column(nullable: true)]
    #[Groups(["users"])]
    private ?float $latitude = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $avatar = null;

    #[ORM\Column(length: 6)]
    #[Assert\NotBlank]
    private ?string $postalCode = null;

    #[ORM\OneToMany(mappedBy: 'member', targetEntity: Bibliogame::class, orphanRemoval: true)]
    private Collection $bibliogames;

    #[ORM\Column(length: 50, unique: true)]
    #[Assert\NotBlank]
    #[Groups(["users", "events"])]
    private ?string $alias = null;

    #[ORM\OneToMany(mappedBy: 'borrowedBy', targetEntity: Bibliogame::class, orphanRemoval: true)]
    private Collection $myBorrowedGames;

    #[ORM\OneToMany(mappedBy: 'userFrom', targetEntity: Chatting::class, orphanRemoval: true)]
    private Collection $chattingsFrom;

    #[ORM\OneToMany(mappedBy: 'userTo', targetEntity: Chatting::class, orphanRemoval: true)]
    private Collection $chattingsTo;

    #[ORM\OneToMany(mappedBy: 'host', targetEntity: Event::class, orphanRemoval: true)]
    private Collection $events;

    #[ORM\OneToMany(mappedBy: 'requestBy', targetEntity: Bibliogame::class, orphanRemoval: true)]
    private Collection $myBibliogameRequest;

    #[ORM\Column(length: 100, nullable: true)]
    private ?string $resetToken = null;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: EventRequests::class, orphanRemoval: true)]
    private Collection $eventRequests;

    #[ORM\OneToMany(mappedBy: 'member', targetEntity: Review::class, orphanRemoval: true)]
    private Collection $reviews;

    public function __construct()
    {
        $this->bibliogames = new ArrayCollection();
        $this->myBorrowedGames = new ArrayCollection();
        $this->chattings = new ArrayCollection();
        $this->events = new ArrayCollection();
        $this->reviews = new ArrayCollection();
        $this->eventRequests = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): static
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): static
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getBirthAt(): ?\DateTimeImmutable
    {
        return $this->birthAt;
    }

    public function setBirthAt(\DateTimeImmutable $birthAt): static
    {
        $this->birthAt = $birthAt;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): static
    {
        $this->address = $address;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): static
    {
        $this->city = $city;

        return $this;
    }

    public function getLongitude(): ?float
    {
        return $this->longitude;
    }

    public function setLongitude(?float $longitude): static
    {
        $this->longitude = $longitude;

        return $this;
    }

    public function getLatitude(): ?float
    {
        return $this->latitude;
    }

    public function setLatitude(?float $latitude): static
    {
        $this->latitude = $latitude;

        return $this;
    }

    public function getAvatar(): ?string
    {
        return $this->avatar;
    }

    public function setAvatar(?string $avatar): static
    {
        $this->avatar = $avatar;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postalCode;
    }

    public function setPostalCode(string $postalCode): static
    {
        $this->postalCode = $postalCode;

        return $this;
    }

    public function __toString()
    {
        //return ucwords($this->firstname.' '.$this->lastname);
        return ucwords($this->alias);
    }

    /**
     * @return Collection<int, Bibliogame>
     */
    public function getBibliogames(): Collection
    {
        return $this->bibliogames;
    }

    public function addBibliogame(Bibliogame $bibliogame): static
    {
        if (!$this->bibliogames->contains($bibliogame)) {
            $this->bibliogames->add($bibliogame);
            $bibliogame->setMember($this);
        }

        return $this;
    }

    public function removeBibliogame(Bibliogame $bibliogame): static
    {
        if ($this->bibliogames->removeElement($bibliogame)) {
            // set the owning side to null (unless already changed)
            if ($bibliogame->getMember() === $this) {
                $bibliogame->setMember(null);
            }
        }

        return $this;
    }

    public function getAlias(): ?string
    {
        return $this->alias;
    }

    public function setAlias(string $alias): static
    {
        $this->alias = $alias;

        return $this;
    }

    /**
     * @return Collection<int, Bibliogame>
     */
    public function getMyBorrowedGames(): Collection
    {
        return $this->myBorrowedGames;
    }

    public function addMyBorrowedGame(Bibliogame $myBorrowedGame): static
    {
        if (!$this->myBorrowedGames->contains($myBorrowedGame)) {
            $this->myBorrowedGames->add($myBorrowedGame);
            $myBorrowedGame->setBorrowedBy($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, Chatting>
     */
    public function getChattingsFrom(): Collection
    {
        return $this->chattingsFrom;
    }

    public function addChattingFrom(Chatting $chatting): static
    {
        if (!$this->chattingsFrom->contains($chatting)) {
            $this->chattingsFrom->add($chatting);
            $chatting->setUseTo($this);
        }

        return $this;
    }
 /**
     * @return Collection<int, Chatting>
     */

     public function getChattingsTo()
     {
        return $this->chattingsTo;
     }
    public function removeMyBorrowedGame(Bibliogame $myBorrowedGame): static
    {
        if ($this->myBorrowedGames->removeElement($myBorrowedGame)) {
            // set the owning side to null (unless already changed)
            if ($myBorrowedGame->getBorrowedBy() === $this) {
                $myBorrowedGame->setBorrowedBy(null);
            }
        }

        return $this;
    }

    public function removeChatting(Chatting $chatting): static
    {
        if ($this->chattings->removeElement($chatting)) {
            // set the owning side to null (unless already changed)
            if ($chatting->getUserFrom() === $this) {
                $chatting->setUserFrom(null);
            }
        }

        return $this;
    }

    /**
     * Return array of Game
     *
     * @return Game[]
     */
    public function getGameCollection()
    {
        $games = [];

templates/game_card/_bibliogame_game_card.html.twig
{# Used in Bibliogame #}
<article id="card{{ game.id }}" class="gamecard card h-100">

    {% include "game_card/_card_header.html.twig" %}

    <div class="card-body">
        <h4 class="title">{{ game.title|title }}</h4> 
    </div>
    <ul class="list-group list-group-flush border-0">

        {% if bibliogame.borrowedBy is not null %}
            <li class="list-group-item border-0">
                Emprunté le {{ bibliogame.borrowedAt|date('j/m/Y') }} par <a href="{{ path('app_profil_public', {id: bibliogame.borrowedBy.id}) }}">{{ bibliogame.borrowedBy.alias }}</a>
            </li>
            <li class="list-group-item text-center border-0">
                <a class='btn rounded-pill btn-primary' href="{{ path('app_bibliogame_return', {id: bibliogame.id}) }}" onclick="return confirm('Le jeu à été récupéré ?');">Jeu récupéré</a>
            </li>
        {% endif %}

        {% if bibliogame.requestBy %}
        <li class="list-group-item border-0">
            Demande de réservation par <a href="{{ path('app_profil_public', {id: bibliogame.requestBy.id}) }}">{{bibliogame.requestBy.alias}}</a>
        </li>
        <li class='list-group-item text-center border-0'>
            <a href="{{path('app_bibliogame_request_accept',{id:bibliogame.id})}}" class='btn rounded-pill btn-success' onclick="return confirm('Accepter la demande de prêt ?');">Accepter</a>
            <a href="{{path('app_bibliogame_request_deny',{id:bibliogame.id})}}" class='btn rounded-pill btn-danger' onclick="return confirm('Refuser la demande de prêt ?');">Refuser</a>
        </li>

        {% endif %}

        <li class="list-group-item border-0">
            <div class="form-check form-switch">
                <input class="form-check-input" type="checkbox" id="switch{{ bibliogame.id }}" value="{{ bibliogame.id }}"
                    {% if bibliogame.isAvailable %}checked{% endif %}>
                <label id="label{{ bibliogame.id }}" class="form-check-label" for="switch{{ bibliogame.id }}">
                    {% if bibliogame.isAvailable %} Disponible {% else %} Indisponible {% endif %} 
                </label>
            </div>
        </li>
        
    </ul>
    
    {% include "game_card/_card_footer.html.twig" %}

</article>

templates/game_card/_borrowed_game_card.html.twig
{# Used in Bibliogame for MyBorrowedGames #}
<article class="gamecard card h-100">
    
    {% include "game_card/_card_header.html.twig" %}

    <div class="card-body">
        <h4 class="title">{{ game.title|title }}</h4> 
    </div>
    <ul class="list-group list-group-flush">
        <li class="list-group-item">
            Emprunté le {{ bibliogame.borrowedAt|date('j/m/Y') }}
        </li>
        <li class="list-group-item">
            à <a href="{{ path('app_profil_public', {id: bibliogame.member.id}) }}" class="card-link">{{ bibliogame.member.alias }}</a>
        </li>
        {# <li class="list-group-item">
            <div class="form-check form-switch">
                <input class="form-check-input" type="checkbox" id="switch{{ bibliogame.id }}"
                    {% if bibliogame.isAvailable %}checked{% endif %} 
                    value="{{ bibliogame.id }}"  disabled>
                <label class="form-check-label" for="switch{{ bibliogame.id }}">Disponible</label>
            </div>
        </li> #}
    </ul>
    
    {# {% include "game_card/_card_footer.html.twig" %} #}

</article>

templates/game_card/_card_footer.html.twig
{% if is_granted('ROLE_USER') %}
    <div class="card-footer text-end border-0 bg-white">
        {# {% if (game in app.user.gameCollection) %}
            <a href="{{ path('app_bibliogame_remove', {gameId: game.id}) }}" class="card_link">Retirer de ma Bibliogame</a>
        {% else %}                    
            <a href="{{ path('app_bibliogame_add', {gameId: game.id}) }}" class="card_link">Ajouter à ma Bibliogame</a>
        {% endif %} #}

        {% set bibliogame = null %}
        {# Récupère la bibliogame du jeu et de l'utilisateur #}
        {% for b in app.user.bibliogames %}
            {% if b.game is same as game %}
                {% set bibliogame = b %}
            {% endif %}
        {% endfor %}

        {# si la bibliogame existe et qu'il y a un emprunt en cours #}
        {% if (bibliogame is not null) and (bibliogame.borrowedBy) %}
                <button class="btn-action btn btn-light rounded-pill" disabled>En cours d'emprunt</button>
        {% else %}
                {% if (game in app.user.gameCollection) %}
                    <button id="action{{ game.id }}" value="{{ game.id }}" class="btn-action btn btn-light rounded-pill" onclick="return confirm('Retirer de ma bilbiogame ?');">
                        <i class="fa-solid fa-minus"></i> Retirer
                {% else %}
                    <button id="action{{ game.id }}" value="{{ game.id }}" class="btn-action btn btn-success rounded-pill">
                        <i class="fa-solid fa-plus"></i> Ajouter
                {% endif %}
            </button>
        {% endif %}

    </div>
{% endif %}

templates/game_card/_card_header.html.twig
<div class="card-header bg-white border-0">
    <a href="{{ path('app_games_details', {slug: game.slug}) }}">
        {% if game.imageUrl %}
            <img class="img-fluid rounded" src="{{ game.imageUrl }}" alt="{{ game.title|title }}">
        {% else %}
            <img class="img-fluid rounded" src="{{ asset('images/ohmygame_logo.png') }}" alt="{{ game.title|title }}">
        {% endif %}
    </a>
</div>

templates/game_card/_game_card.html.twig
<article id="card{{ game.id }}" class="gamecard card h-100">
    
    {% include "game_card/_card_header.html.twig" %}

    <div class="card-body">
        <h4 class="title">{{ game.title|title }}</h4> 
        {% set rating = game.rating %}
        {% include "partials/_star_counter.html.twig" %}
        <p>{{ game.shortDescription }}</p>
        {# <hr>
        {% for theme in game.theme %}
            {{ theme }}
        {% endfor %} #}
    </div>
    
    {% include "game_card/_card_footer.html.twig" %}

</article>

templates/game_card/_game_card_line.html.twig
<article class="row py-4">
    <div class="col-4">
        <div class="mx-auto p-2 border rounded">
            <img class="img-fluid rounded" src="{{ game.imageUrl }}" alt="{{ game.title|title }}">
        </div>
    </div>
    <div class="col-8">
        <h2>{{ game.title|title }}</h2>
        {% set rating = game.rating %}
        {% include "partials/_star_counter.html.twig" %}
        <p>{{ game.shortDescription }}</p>
        <a href="{{ path('app_games_details', {slug: game.slug}) }}" class="btn btn-primary">Détails ...</a>
        {# {% if app.user %} #}
            {# {% if game in app.user.bibliogames %} #}
                <a href="{{ path('app_bibliogame_add', {id: game.id}) }}" class="btn btn-primary">Ajouter à ma Bibliogame</a>
            {# {% else %}                     #}
                <a href="" class="btn btn-primary">Retirer de ma Bibliogame</a>
            {# {% endif %} #}
        {# {% endif %} #}
    </div>
</article>

templates/game_card/_game_card_title.html.twig
<article class="card h-100 border-0">
    <a href="{{ path('app_games_details', {slug: game.slug}) }}">
        {% if game.imageUrl %}
            <img class="img-fluid rounded" src="{{ game.imageUrl }}" alt="{{ game.title|title }}">
        {% else %}
            <img class="img-fluid rounded" src="{{ asset('images/ohmygame_logo.png') }}" alt="{{ game.title|title }}">
        {% endif %}
    </a>
    <div class="card-body text-center">
        <h4 class="title">{{ game.title|title }}</h4>
        <p>{{ game.shortDescription}}</p>
    </div>
</article>

templates/game_card/_public_bibliogame_game_card.html.twig
{# Used in Bibliogame #}
<article id="card{{ game.id }}" class="gamecard card h-100">

    {% include "game_card/_card_header.html.twig" %}

    <div class="card-body">
        <h4 class="title">{{ game.title|title }}</h4> 
    </div>

    <div class="card-footer border-0 bg-white text-center">
        {% if bibliogame.isAvailable %}
            {% if not bibliogame.borrowedBy %}
                {% if bibliogame.requestBy %} 
                    <button class="btn-action btn btn-light rounded-pill" disabled>En cours de réservation</button>
                {% else %}
                    <a href="{{path("app_bibliogame_request",{id:bibliogame.id})}}" class="btn btn-success rounded-pill">Faire une demande d'emprunt</a> 
                {% endif %}
            {% else %}
                <button class="btn-action btn btn-light rounded-pill" disabled>En cours d'emprunt</button>
            {% endif %}
        {% else %} 
            <button class="btn-action btn btn-light rounded-pill" disabled>Disponible avec {{bibliogame.member.alias}} !</button>
        {% endif %}
    </div>
</article>